name: ambulance_emergency_system
description: A Flutter application for ambulance emergency response system.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^4.2.2
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  intl: ^0.18.1
  google_maps_flutter: ^2.5.0
  # OpenStreetMap packages
  flutter_map: ^6.0.1
  latlong2: ^0.9.0
  # Location tracking
  geolocator: ^10.1.0
  permission_handler: ^11.0.1
  # UI packages
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

